name: Flip Software/Hardware Badges

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  flip-badges:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Flip badges
      run: |
        # Read README
        content=$(cat README.md)
        
        # Check if currently showing Software or Hardware
        if echo "$content" | grep -q "Software%2FHardware"; then
          # Currently showing Software/Hardware, change to just Software
          content=$(echo "$content" | sed 's/Software%2FHardware/Software/g')
          content=$(echo "$content" | sed 's/Software%2FHardware-FF6B6B/Software-FF6B6B/g')
        else
          # Currently showing Software, change to Hardware
          content=$(echo "$content" | sed 's/Software/Hardware/g')
          content=$(echo "$content" | sed 's/visual-studio/chip/g')
          content=$(echo "$content" | sed 's/FF6B6B/00D4AA/g')
        fi
        
        # Write back to README
        echo "$content" > README.md
            
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Flip Software/Hardware badge"
        git push
